# Generated by Django 4.0.5 on 2022-08-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termsgen', '0002_rename_bussiness_name_database_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='database',
            new_name='basic',
        ),
    ]
