# Generated by Django 4.0.5 on 2022-08-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsgen', '0003_rename_database_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_Address', models.CharField(max_length=23, null=True)),
                ('password', models.CharField(max_length=23, null=True)),
            ],
        ),
    ]
