# Generated by Django 4.0.5 on 2022-08-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsgen', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='USERNAME',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email_Address',
            field=models.EmailField(max_length=23, null=True),
        ),
    ]
