# Generated by Django 4.0.5 on 2022-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsgen', '0005_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
